"""Slot 22 — the verifier gate.

Everything the execution plane produces passes a deterministic check before it is
trusted. Not an LLM judge: the verdict is also the training signal, and a signal
generated by a model is a signal that can be wrong in the same direction as the
thing it is grading.

**Verifiers come in two kinds, and the difference is about time, not accuracy.**

* **Static** — syntax, AST, JSON schema, SymPy. Sub-second. Run inline; the
  orchestrator simply waits.
* **Stateful** — did the server bind to 8080, did ``npm install`` finish, does
  the endpoint answer. Seconds to minutes.

For stateful checks the rule is: **never let a model wait.** The orchestrator
starts the work, polls mechanically, and the model holds no context while that
happens. Below ``suspend_threshold_seconds`` awaiting inline is simpler than
serialising a task to disk and back, so suspension is a threshold rather than an
absolute (Slot 25).

A verifier that crashes is not a failed verification. ``Verdict.errored`` exists
so a broken check is classed as TRANSPORT — it retries at the same tier, does not
escalate, and never becomes a training label. Grading a model down because your
own tooling broke would poison the router quietly and permanently.
"""

from __future__ import annotations

import abc
from enum import Enum
from pathlib import Path

from certify.core.schemas import Strict, TaskSpec, Verdict


class VerifierKind(str, Enum):
    STATIC = "static"
    STATEFUL = "stateful"


class VerifyContext(Strict):
    """What a verifier is given.

    Deliberately small. A verifier that needed the conversation, the model, or
    the attempt history would be judging the process rather than the artefact,
    and the whole point of the gate is that it looks only at what was produced.
    """

    task_id: str
    spec: TaskSpec | None = None

    workspace: Path
    """Jail-resolved root. Verifiers receive an already-approved path; they do
    not consult the guard themselves."""

    changed_paths: list[str] = []
    """Jail-relative paths the attempt claims to have touched."""

    target: str | None = None
    """Verifier-specific: a test path, a URL, a port."""

    model_config = {"arbitrary_types_allowed": True, "extra": "forbid"}


class Verifier(abc.ABC):
    """One deterministic check."""

    name: str
    kind: VerifierKind = VerifierKind.STATIC

    expected_seconds: float = 0.0
    """Rough cost hint. Only consulted for stateful checks, to decide between
    awaiting inline and suspending the task."""

    @abc.abstractmethod
    async def verify(self, ctx: VerifyContext) -> Verdict:
        """Produce a verdict. Must not raise for an ordinary failure.

        Implementations catch their own breakage and return
        :meth:`Verdict.errored`, so infrastructure faults stay distinguishable
        from a model that got the answer wrong.
        """

    def applies_to(self, ctx: VerifyContext) -> bool:
        """Whether this verifier has anything to say about this attempt."""
        return True


class UnknownVerifier(Exception):
    pass


class VerifierRegistry:
    """The gate: the verifiers that apply, run in a defined order."""

    def __init__(self) -> None:
        self._verifiers: dict[str, Verifier] = {}

    def register(self, verifier: Verifier) -> Verifier:
        self._verifiers[verifier.name] = verifier
        return verifier

    def get(self, name: str) -> Verifier:
        try:
            return self._verifiers[name]
        except KeyError:
            known = ", ".join(sorted(self._verifiers)) or "none"
            raise UnknownVerifier(f"no verifier named {name!r}; known: {known}") from None

    def names(self) -> tuple[str, ...]:
        return tuple(sorted(self._verifiers))

    def applicable(self, ctx: VerifyContext) -> list[Verifier]:
        """Verifiers that apply, cheapest first.

        Static checks run before stateful ones so a syntax error is caught for
        free rather than after a sixty-second server poll. Ties break on name, so
        the order is stable and a failure is reproducible.
        """
        chosen = [v for v in self._verifiers.values() if v.applies_to(ctx)]
        return sorted(chosen, key=lambda v: (v.kind is VerifierKind.STATEFUL, v.name))

    async def run(self, ctx: VerifyContext) -> Verdict:
        """Run the gate. Stops at the first failure.

        Short-circuiting is deliberate: the failure reason goes verbatim into the
        retry, and a wall of downstream errors caused by one broken file is worse
        input than the single root cause.
        """
        last: Verdict | None = None
        for verifier in self.applicable(ctx):
            last = await verifier.verify(ctx)
            if not last.ok:
                return last
        if last is None:
            return Verdict.passed("gate", **{"note": "no verifier applied"})
        return last
