"""Slot 07 — the markdown failsafe.

A plain-markdown file the orchestrator keeps up to date at every checkpoint. It
lands this early on the principle that a failsafe has to exist before the things
it is meant to catch.

**Generated deterministically from SQLite. Never written by a model.** That is
the whole point: it costs nothing, it cannot hallucinate, and it says exactly
what the system actually believes rather than what a summariser thought was
worth mentioning.

It earns its place four times over:

* **Recovery.** If the database is corrupt or gone, the journal alone is enough
  to rebuild the tasks and their attempt history.
* **A window.** A human can open one file and see what the daemon thinks is
  happening, without a UI, a query, or a running process.
* **Bootstrap context.** It is a plain document, so it can be handed to *any*
  model — a fresh conductor, a different vendor, a chat window — when something
  needs to be picked up cold.
* **A steering seam.** It is human-editable. Correct the state block and the
  orchestrator reads the correction back.

The file has two halves. The prose is for people and is regenerated wholesale on
every write. The fenced ``aop-state`` block is the authority — machine-written,
machine-read, and the only part that survives a round trip. Recovery parses the
fence rather than the prose, because a parser that reverse-engineers English is
the sort of thing that works in a test and fails in reality.
"""

from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime
from decimal import Decimal
from pathlib import Path

from aop.core.events import EventBus, JournalWritten
from aop.core.ids import Clock, SystemClock
from aop.core.schemas import Attempt, Strict, Task, TaskStatus
from aop.core.state import StateStore

JOURNAL_VERSION = 1
FENCE_TAG = "aop-state"

_FENCE = re.compile(
    r"^```" + re.escape(FENCE_TAG) + r"\s*\n(?P<body>.*?)^```\s*$",
    re.DOTALL | re.MULTILINE,
)


class JournalError(Exception):
    pass


class JournalSnapshot(Strict):
    """The machine-readable half: everything needed to rebuild state."""

    journal_version: int = JOURNAL_VERSION
    generated_at: datetime
    tasks: list[Task]
    attempts: dict[str, list[Attempt]]

    def state_digest(self) -> str:
        """Fingerprint of the state, deliberately excluding ``generated_at``.

        Lets the writer skip a rewrite when nothing has actually changed, so the
        file's timestamp means "state last changed" rather than "we looped again".
        """
        payload = self.model_dump(mode="json", exclude={"generated_at"})
        canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _money(amount: Decimal) -> str:
    return f"${amount:.4f}"


def _fence(snapshot: JournalSnapshot) -> str:
    payload = snapshot.model_dump(mode="json")
    body = json.dumps(payload, sort_keys=True, indent=2)
    return f"```{FENCE_TAG}\n{body}\n```"


def render(snapshot: JournalSnapshot) -> str:
    """Render the journal. Pure and deterministic — same snapshot, same bytes."""
    lines: list[str] = [
        "# Operator Journal",
        "",
        "Generated by the orchestrator directly from durable state. No model wrote",
        "any part of this file, so nothing in it is invented.",
        "",
        "The prose below is regenerated on every write and is safe to ignore. The",
        f"`{FENCE_TAG}` block at the end is the authority: it is what recovery reads,",
        "and editing it is how you correct the system's view of the world.",
        "",
        f"Last state change: {snapshot.generated_at.isoformat()}",
        "",
    ]

    active = [t for t in snapshot.tasks if not t.status.terminal]
    finished = [t for t in snapshot.tasks if t.status.terminal]
    waiting = [t for t in snapshot.tasks if t.status is TaskStatus.AWAITING_HUMAN]

    lines += ["## Summary", ""]
    if not snapshot.tasks:
        lines += ["No tasks recorded.", ""]
    else:
        total = sum((t.cost_usd for t in snapshot.tasks), Decimal("0"))
        lines += [
            f"- Tasks: {len(snapshot.tasks)} ({len(active)} active, {len(finished)} finished)",
            f"- Attempts: {sum(len(v) for v in snapshot.attempts.values())}",
            f"- Spend: {_money(total)}",
            "",
        ]

    if waiting:
        lines += [
            "## Waiting on you",
            "",
            "These stopped because the next decision has no verifier behind it.",
            "",
        ]
        for task in waiting:
            lines.append(f"- **{task.task_id}** — {task.note or task.directive}")
        lines.append("")

    if snapshot.tasks:
        lines += [
            "## Tasks",
            "",
            "| Task | Status | Attempts | Spend | Directive |",
            "|---|---|---|---|---|",
        ]
        for task in snapshot.tasks:
            directive = task.directive.replace("|", "\\|").replace("\n", " ")
            if len(directive) > 60:
                directive = directive[:57] + "..."
            lines.append(
                f"| {task.task_id} | {task.status.value} | {task.attempt_count} "
                f"| {_money(task.cost_usd)} | {directive} |"
            )
        lines.append("")

    for task in snapshot.tasks:
        lines += [f"## {task.task_id} — {task.status.value}", ""]
        lines += ["**Directive** (verbatim, immutable):", "", f"> {task.directive}", ""]

        if task.status is TaskStatus.SUSPENDED:
            detail = f"Suspended: {task.suspended_reason or 'unspecified'}"
            if task.resume_after:
                detail += f" (resume after {task.resume_after.isoformat()})"
            lines += [detail, ""]
        if task.note:
            lines += [f"Note: {task.note}", ""]

        if task.spec:
            spec = task.spec
            lines += [f"**Goal:** {spec.goal}", ""]
            if spec.acceptance:
                lines += ["Acceptance criteria:", ""]
                lines += [f"- {c}" for c in spec.acceptance]
                lines.append("")
            if spec.artifacts:
                lines += [f"Artifacts: {', '.join(spec.artifacts)}", ""]

        if task.cost_usd:
            lines += [f"**Spend:** {_money(task.cost_usd)}", ""]

        attempts = snapshot.attempts.get(task.task_id, [])
        if attempts:
            lines += [
                "| # | Tier | Model | Verdict | Class | Spend | Reason |",
                "|---|---|---|---|---|---|---|",
            ]
            for a in attempts:
                reason = (a.failure_reason or "").replace("|", "\\|").replace("\n", " ")
                if len(reason) > 50:
                    reason = reason[:47] + "..."
                lines.append(
                    f"| {a.index} | {a.role.value} | {a.model_id} | {a.verdict.value} "
                    f"| {a.failure_class.value} | {_money(a.cost_usd)} | {reason} |"
                )
            lines.append("")

    lines += [
        "## Machine state",
        "",
        "Authoritative. Recovery reads this block and ignores everything above it.",
        "",
        _fence(snapshot),
        "",
    ]
    return "\n".join(lines)


def parse(text: str) -> JournalSnapshot:
    """Read the state block back out of a journal file."""
    match = _FENCE.search(text)
    if match is None:
        raise JournalError(f"no ```{FENCE_TAG} block found — cannot recover from prose")
    try:
        payload = json.loads(match.group("body"))
    except json.JSONDecodeError as exc:
        raise JournalError(f"state block is not valid JSON: {exc}") from exc

    version = payload.get("journal_version")
    if version != JOURNAL_VERSION:
        raise JournalError(
            f"journal version {version!r} is not readable by this build "
            f"(expected {JOURNAL_VERSION})"
        )
    return JournalSnapshot.model_validate(payload)


async def snapshot_state(store: StateStore, clock: Clock) -> JournalSnapshot:
    """Read the whole world out of SQLite, in a stable order."""
    tasks = await store.list_tasks()
    attempts = {t.task_id: await store.list_attempts(t.task_id) for t in tasks}
    return JournalSnapshot(
        generated_at=clock.now(),
        tasks=tasks,
        attempts={k: v for k, v in attempts.items() if v},
    )


async def restore(store: StateStore, snapshot: JournalSnapshot) -> int:
    """Rebuild state from a snapshot into a store.

    Uses the raw upserts rather than the normal creation path: recovery must
    reproduce what was there, not mint a plausible replacement with fresh ids
    and a recomputed directive hash.
    """
    await store.migrate()
    restored = 0
    for task in snapshot.tasks:
        await store.upsert_task(task)
        restored += 1
    for attempts in snapshot.attempts.values():
        for attempt in attempts:
            await store.upsert_attempt(attempt)
    return restored


class Journal:
    """Keeps ``OPERATOR.md`` in step with durable state."""

    def __init__(
        self,
        store: StateStore,
        path: Path | str,
        bus: EventBus | None = None,
        clock: Clock | None = None,
    ) -> None:
        self._store = store
        self._path = Path(path)
        self._bus = bus
        self._clock = clock or SystemClock()
        self._last_digest: str | None = None

    @property
    def path(self) -> Path:
        return self._path

    async def write(self, *, force: bool = False) -> bool:
        """Regenerate the journal. Returns True if the file was written.

        Skips the write when the state digest is unchanged, so calling this on
        every checkpoint is cheap and the file's timestamp stays meaningful.
        """
        snapshot = await snapshot_state(self._store, self._clock)
        digest = snapshot.state_digest()
        if not force and digest == self._last_digest and self._path.exists():
            return False

        self._path.parent.mkdir(parents=True, exist_ok=True)
        # newline="\n" keeps the bytes identical across platforms; without it
        # Windows would rewrite every "\n" and break the byte-stability test.
        self._path.write_text(render(snapshot), encoding="utf-8", newline="\n")
        self._last_digest = digest

        if self._bus:
            self._bus.emit(JournalWritten, path=str(self._path), digest=digest)
        return True

    def read_snapshot(self) -> JournalSnapshot:
        if not self._path.is_file():
            raise JournalError(f"journal not found: {self._path}")
        return parse(self._path.read_text(encoding="utf-8"))

    async def recover(self) -> int:
        """Rebuild the store from the journal on disk.

        The last-resort path: SQLite is gone or unreadable, and this file is all
        that is left.
        """
        return await restore(self._store, self.read_snapshot())
